## Deliverable 2. Create a Customer Travel Destinations Map.

In [6]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [8]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("WeatherPy_database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Weather Description
0,0,Korla,CN,41.7597,86.1469,70.86,13,0,8.39,clear sky
1,1,Albany,US,42.6001,-73.9662,74.57,35,11,8.25,few clouds
2,2,Pasni,PK,25.2631,63.4710,81.19,86,0,11.12,clear sky
3,3,Sao Filipe,CV,14.8961,-24.4956,75.54,73,2,12.35,clear sky
4,4,Longyearbyen,SJ,78.2186,15.6401,42.64,87,75,9.22,broken clouds

In [9]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [10]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Weather Description
2,2,Pasni,PK,25.2631,63.4710,81.19,86,0,11.12,clear sky
3,3,Sao Filipe,CV,14.8961,-24.4956,75.54,73,2,12.35,clear sky
15,15,San Policarpo,PH,12.1791,125.5072,77.52,85,94,2.86,overcast clouds
19,19,Vaini,TO,-21.2000,-175.2000,80.76,74,20,4.61,few clouds
21,21,Hue,VN,16.4667,107.6000,82.51,78,20,5.75,few clouds
25,25,Axim,GH,4.8699,-2.2405,77.47,87,99,10.09,light rain
33,33,Atuona,PF,-9.8000,-139.0333,78.30,72,56,15.21,broken clouds
43,43,Palmer,US,42.1584,-72.3287,76.21,35,40,8.05,scattered clouds
47,47,Faanui,PF,-16.4833,-151.7500,79.66,76,67,13.18,light rain
48,48,Puerto Ayora,EC,-0.7393,-90.3518,75.16,91,97,8.01,overcast clouds

In [11]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.count()

City_ID                214
City                   214
Country                214
Lat                    214
Lng                    214
Max Temp               214
Humidity               214
Cloudiness             214
Wind Speed             214
Weather Description    214
dtype: int64

In [6]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
#N/A

In [13]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Weather Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Weather Description,Lat,Lng,Hotel Name
2,Pasni,PK,81.19,clear sky,25.2631,63.4710,
3,Sao Filipe,CV,75.54,clear sky,14.8961,-24.4956,
15,San Policarpo,PH,77.52,overcast clouds,12.1791,125.5072,
19,Vaini,TO,80.76,few clouds,-21.2000,-175.2000,
21,Hue,VN,82.51,few clouds,16.4667,107.6000,
25,Axim,GH,77.47,light rain,4.8699,-2.2405,
33,Atuona,PF,78.30,broken clouds,-9.8000,-139.0333,
43,Palmer,US,76.21,scattered clouds,42.1584,-72.3287,
47,Faanui,PF,79.66,light rain,-16.4833,-151.7500,
48,Puerto Ayora,EC,75.16,overcast clouds,-0.7393,-90.3518,

In [14]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    params["location"] = f"{lat},{lng}"
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [16]:
hotel_df.head(10)

,City,Country,Max Temp,Weather Description,Lat,Lng,Hotel Name
2,Pasni,PK,81.19,clear sky,25.2631,63.4710,Kashmiri Hotal
3,Sao Filipe,CV,75.54,clear sky,14.8961,-24.4956,Hotel Xaguate
15,San Policarpo,PH,77.52,overcast clouds,12.1791,125.5072,Agapita M. Nicart
19,Vaini,TO,80.76,few clouds,-21.2000,-175.2000,Keleti Beach Resort
21,Hue,VN,82.51,few clouds,16.4667,107.6000,Saigon Morin Hotel
25,Axim,GH,77.47,light rain,4.8699,-2.2405,Axim Beach Resort And Spa
33,Atuona,PF,78.30,broken clouds,-9.8000,-139.0333,Villa Enata
43,Palmer,US,76.21,scattered clouds,42.1584,-72.3287,Wedgewood Motel
47,Faanui,PF,79.66,light rain,-16.4833,-151.7500,Bora-Bora Pearl Beach Resort & Spa
48,Puerto Ayora,EC,75.16,overcast clouds,-0.7393,-90.3518,Finch Bay Galapagos Hotel

In [18]:
# 7. Drop the rows where there is no Hotel Name.
hotel_df.count()

City                   214
Country                214
Max Temp               214
Weather Description    214
Lat                    214
Lng                    214
Hotel Name             214
dtype: int64

In [21]:
# 8a. Create the output File (CSV)
output_data_file = "WeaterPy_Vacation"
# 8b. Export the City_Data into a csv
hotel_df.to_csv(output_data_file, index_label="City_ID")

In [24]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = hotel_df[["Lat", "Lng"]]

In [25]:
# 11a. Add a marker layer for each city to the map. 
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))